# Generated by Django 5.2.6 on 2026-05-22 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counting', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='peoplecount',
            new_name='counting_pe_hall_id_43a6aa_idx',
            old_name='peoplecount_hall_time_idx',
        ),
    ]
