# Generated by Django 5.2.6 on 2026-05-22 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_toyxona_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='camera',
            new_name='camera_came_hall_id_6ab9d3_idx',
            old_name='camera_hall_sn_idx',
        ),
    ]
